export {default as Navar } from './Navbar'
export {default as Hero } from './Hero'
export {default as Blog } from './Blog'
export {default as ContactUs } from './ContactUs'
export {default as Knowledge } from './Knowledge'